name: PR on main - Render and push changed files

on:
  push:
    branches: 'main'
  pull_request:
    branches: 'main'
jobs:
  render-files:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input name to STDOUT
        run: echo The username is ${{ inputs.username }}

      - name: Setup GitHub repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: true  # Fetch latex-math
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Install latex
        run: sudo apt-get install -y latexmk texlive-full

      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install knitr
        run: Rscript -e 'install.packages("knitr")'

      - name: Test make
        run: |
          cd slides
          make changes
          cd ../exercises
          make
          #cd ../code-demos
          #make

      - name: Set env for GITSTATUS
        run: echo "GITSTATUS=$(git status -s | wc -l)" >> $GITHUB_ENV

      - name: Commit files
        if: ${{ env.GITSTATUS != 0 }}
        run: |
           git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
           git config --local user.name "github-actions[bot]"
           git add slides-pdf/*.pdf
           git add exercises-pdf/*.pdf
           git commit -m "Add pdf files"

      - name: Push changes
        uses: ad-m/github-push-action@master
        if: ${{ env.GITSTATUS != 0 }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
