name: Render tex files

on:
  push:
    branches: 'main'

jobs:
  render-files:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input name to STDOUT
        run: echo The username is ${{ inputs.username }}

      - name: Setup GitHub repository
        uses: actions/checkout@v2
        with:
          submodules: true  # Fetch latex-math
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    #      - uses: r-lib/actions/setup-r@v1
    #      - uses: r-lib/actions/setup-pandoc@v1
    #
    #      - name: Install rmarkdown
    #        run: Rscript -e 'install.packages("knitr")'
    #
    #      - name: Setup texlive
    #      - uses: xu-cheng/texlive-action/full@v1
    #        with:
    #          run: |
    #            apk add make
    #            make slides/tex.mk
    #            make exercises/Makefile
    #            make code-demos/Makefile
    #
    #      - name: Commit files
    #        run: |
    #          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
    #          git config --local user.name "github-actions[bot]"
    #          git commit -m "Add pdf files" -a
    #
    #      - name: Push changes
    #        uses: ad-m/github-push-action@master
    #        with:
    #          github_token: ${{ secrets.GITHUB_TOKEN }}
    #          branch: 'main'
